environments:
  benrd:
  bingrd:
  dev:
  prod-blue:
  prod-green:
  prototype:


releases:

  - name: oasubapi-{{ requiredEnv "BRANCH" }}
    chart: ../helm/charts/oas-unblock-bot
    namespace: oas-ub-{{ requiredEnv "BRANCH" }}
    values:
      - overrides/oas-unblock-bot-api.yaml.gotmpl
    labels:
        category: prototype
        app: oas-unblock-bot
        tier: api
    wait: false
    installed: true
    force: false